CHANGELOG.md
CONTRIBUTING.md
__tests__/spot/bswap/bswapClaimRewards.test.js
__tests__/spot/bswap/bswapClaimedHistory.test.js
__tests__/spot/bswap/bswapUnclaimedRewards.test.js
__tests__/spot/mining/miningAccountEarning.test.js
__tests__/spot/sub_account/subAccountFuturesAccountSummaryV2.test.js
__tests__/spot/sub_account/subAccountFuturesAccountV2.test.js
__tests__/spot/sub_account/subAccountFuturesPositionRiskV2.test.js
__tests__/spot/sub_account/subAccountUniversalTransfer.test.js
__tests__/spot/sub_account/subAccountUniversalTransferHistory.test.js
examples/spot/bswap/bswapClaimRewards.js
examples/spot/bswap/bswapClaimedHistory.js
examples/spot/bswap/bswapUnclaimedRewards.js
examples/spot/mining/miningAccountEarning.js
examples/spot/sub_account/subAccountFuturesAccountSummaryV2.js
examples/spot/sub_account/subAccountFuturesAccountV2.js
examples/spot/sub_account/subAccountFuturesPositionRiskV2.js
examples/spot/sub_account/subAccountUniversalTransfer.js
examples/spot/sub_account/subAccountUniversalTransferHistory.js
package-lock.json
package.json
src/modules/bswap.js
src/modules/margin.js
src/modules/mining.js
src/modules/subAccount.js

- `GET /sapi/v1/mining/payment/uid` to get Mining account earning
- `GET /sapi/v1/bswap/unclaimedRewards` to get unclaimed rewards record
- `POST /sapi/v1/bswap/claimRewards` to claim swap rewards or liquidity rewards
- `GET /sapi/v1/bswap/claimedHistory` to get history of claimed rewards
- `POST /sapi/v1/sub-account/universalTransfer` to transfer spot and futures asset between master account and sub accounts
- `GET /sapi/v1/sub-account/universalTransfer` to search transfer records
- `GET /sapi/v2/sub-account/futures/account` to get detail on sub-account's USDT margined futures account and COIN margined futures account
- `GET /sapi/v2/sub-account/futures/accountSummary` to get summary of sub-account's USDT margined futures account and COIN margined futures account
- `GET …

Release v1.7.0

---

package-lock.json

Based on https://github.com/advisories/GHSA-xvch-5gv4-984h, we need to upgrade this minimist package, which is required by jest.

upgrade minimist

---

__tests__/spot/savings/savingsCustomizedPosition.test.js
__tests__/spot/savings/savingsFlexibleProductPosition.test.js
src/modules/savings.js

Sync `savingsCustomizedPosition` and `savingsFlexibleProductPosition` with docs definition:
- https://binance-docs.github.io/apidocs/spot/en/#get-flexible-product-position-user_data
- https://binance-docs.github.io/apidocs/spot/en/#get-fixed-activity-project-position-user_data
For both of them, `asset` is not a required parameter. Because with the current implementation, there is no way to get all positions in one query. Related issue: https://github.com/binance/binance-connector-node/issues/107

fix(savings): make asset optional param

---

src/websocketBase.js

In my effort to maintain clean and understandable code, a few areas of improvement were identified in `src/websocketBase.js`:
1. The existing `if` statement can be made more concise without losing its intent, making it easier for contributors to grasp the logic.
2. A parameter documented in the JSDoc for the `disconnect` function doesn't align with its actual usage. To prevent confusion and potential mishandling in the future, it's proposed to remove this from the JSDoc.

refactor: simplified if statement, removed incorrect param from JSDoc

---

README.md

The "Key Pair Based Authentication" example contains an error in the passed parameters. The proposed correction fixes this error.

fix: spot params example

---

CHANGELOG.md
docs_src/gettingStarted.md
examples/websocketAPI/spot/market/historicalTrades.js
examples/websocketAPI/spot/trade/cancelOCOOrder.js
examples/websocketAPI/spot/trade/cancelOpenOrders.js
examples/websocketAPI/spot/trade/cancelOrder.js
examples/websocketAPI/spot/trade/cancelReplaceOrder.js
examples/websocketAPI/spot/trade/getOCOOpenOrders.js
examples/websocketAPI/spot/trade/getOCOOrder.js
examples/websocketAPI/spot/trade/getOrder.js
examples/websocketAPI/spot/trade/newOCOOrder.js
examples/websocketAPI/spot/trade/newOrder.js
examples/websocketAPI/spot/trade/openOrders.js
examples/websocketAPI/spot/trade/testNewOrder.js
examples/websocketStream/spot/combinedStreams.js
examples/websocketStream/spot/multiSubscription.js
package-lock.json
package.json
src/websocketStream.js

- Updated dependencies
- Resolved multiple websocket stream request issue

Release v3.4.0

---

CHANGELOG.md
__tests__/spot/trade/newOCOOrder.test.js
__tests__/testUtils/mockData.js
examples/spot/trade/newOCOOrder.js
examples/websocketAPI/spot/trade/newOCOOrder.js
package-lock.json
package.json
src/modules/restful/trade.js
src/modules/websocket/api/trade.js

- Updated dependencies
- Upgraded deprecated spot endpoint `POST /api/v3/order/oco` to `POST /api/v3/orderList/oco`
- Upgraded deprecated Websocket API endpoint `orderList.place` to `orderList.place.oco`

Release v3.4.1

---

CHANGELOG.md
__tests__/spot/gift_card/giftCardBuyCode.test.js
examples/spot/gift_card/giftCardBuyCode.js
src/modules/restful/giftCard.js

This pull request adds a new method `giftCardBuyCode` to the GiftCard class in order to create a dual-token gift card using the Binance API.
Added a new method giftCardBuyCode to the GiftCard class.
The giftCardBuyCode method makes a POST request to /sapi/v1/giftcard/buyCode endpoint.
The method takes the token you want to pay, the token you want to buy, the base token asset quantity, the card discount percentage in option and optional options parameter to specify additional query parameters.
The method returns the code of the gift card.
```
// Assuming you have an instance of the client
const client = new Spot(apiKey, apiSecret)
// Specify the symbol and options (if needed)
const baseToken = 'USDT';
const faceToken = 'BTC';
const options = {
// Add any additional options if required
}; …
```

Add method giftCardBuyCode in order to create a dual-token gift card

---

CHANGELOG.md
docs_src/docs.sh
package-lock.json
package.json
src/modules/restful/market.js
src/modules/restful/stream.js
src/modules/restful/trade.js
src/modules/websocket/api/account.js
src/modules/websocket/api/market.js
src/modules/websocket/api/trade.js
src/modules/websocket/api/userData.js

- Updated documentation links.

Release v3.6.1

---

clients/dual-investment/CHANGELOG.md
clients/dual-investment/README.md
clients/dual-investment/package-lock.json
clients/dual-investment/package.json
clients/dual-investment/src/index.ts
clients/dual-investment/src/rest-api/index.ts
clients/dual-investment/src/rest-api/modules/index.ts
clients/dual-investment/src/rest-api/modules/market-data-api.ts
clients/dual-investment/src/rest-api/modules/trade-api.ts
clients/dual-investment/src/rest-api/rest-api.ts
clients/dual-investment/src/rest-api/types/bad-request.ts
clients/dual-investment/src/rest-api/types/change-auto-compound-status-response.ts
clients/dual-investment/src/rest-api/types/check-dual-investment-accounts-response.ts
clients/dual-investment/src/rest-api/types/get-dual-investment-positions-response-list-inner.ts
clients/dual-investment/src/rest-api/types/get-dual-investment-positions-response.ts
clients/dual-investment/src/rest-api/types/get-dual-investment-product-list-response-list-inner.ts
clients/dual-investment/src/rest-api/types/get-dual-investment-product-list-response.ts
clients/dual-investment/src/rest-api/types/subscribe-dual-investment-products-response.ts
clients/dual-investment/tests/unit/rest-api/MarketDataApiTest.test.ts
clients/dual-investment/tests/unit/rest-api/TradeApiTest.test.ts

Release dual-investment v1.0.1

---

clients/copy-trading/CHANGELOG.md
clients/copy-trading/README.md
clients/copy-trading/package-lock.json
clients/copy-trading/package.json
clients/copy-trading/src/index.ts
clients/copy-trading/src/rest-api/index.ts
clients/copy-trading/src/rest-api/modules/future-copy-trading-api.ts
clients/copy-trading/src/rest-api/modules/index.ts
clients/copy-trading/src/rest-api/rest-api.ts
clients/copy-trading/src/rest-api/types/bad-request.ts
clients/copy-trading/src/rest-api/types/get-futures-lead-trader-status-response-data.ts
clients/copy-trading/src/rest-api/types/get-futures-lead-trader-status-response.ts
clients/copy-trading/src/rest-api/types/get-futures-lead-trading-symbol-whitelist-response-data-inner.ts
clients/copy-trading/src/rest-api/types/get-futures-lead-trading-symbol-whitelist-response.ts
clients/copy-trading/tests/unit/rest-api/FutureCopyTradingApiTest.test.ts

Release copy-trading v1.0.1

---

types/CHANGELOG.md
types/package-lock.json
types/package.json

- Update `@binance/common` library to version `1.0.2`.

Release types v1.0.2

---

common/CHANGELOG.md

- Update `replaceWebsocketStreamsPlaceholders` function to parse `updateSpeed` properly.

Release common v1.0.2

---

clients/simple-earn/CHANGELOG.md
clients/simple-earn/package-lock.json
clients/simple-earn/package.json
clients/simple-earn/src/rest-api/modules/history-api.ts
clients/simple-earn/tests/unit/rest-api/HistoryApiTest.test.ts

- Added `current`, `size` and `recvWindow` parameters to `/sapi/v1/simple-earn/flexible/history/rewardsRecord`.

Release simple-earn v3.0.0

---

clients/spot/CHANGELOG.md
clients/spot/package-lock.json
clients/spot/package.json
clients/spot/src/rest-api/types/index.ts
clients/spot/src/rest-api/types/klines-item-inner.ts
clients/spot/src/rest-api/types/klines-item.ts
clients/spot/src/websocket-api/types/index.ts
clients/spot/src/websocket-api/types/klines-item-inner.ts
clients/spot/src/websocket-api/types/ui-klines-item.ts

- Modified `klines()` (response type changed - it can be either a number or string)
- Modified `uiKlines()` (response type changed - it can be either a number or string)
- Modified `klines()` (response type changed - it can be either a number or string)
- Modified `uiKlines()` (response type changed - it can be either a number or string)

Release spot v6.0.0

---

clients/derivatives-trading-portfolio-margin-pro/CHANGELOG.md
clients/derivatives-trading-portfolio-margin-pro/package-lock.json
clients/derivatives-trading-portfolio-margin-pro/package.json
clients/derivatives-trading-portfolio-margin-pro/src/index.ts
clients/derivatives-trading-portfolio-margin-pro/src/rest-api/modules/account-api.ts

- Marked as signed the following endpoints:
- `POST /sapi/v1/portfolio/repay`
- Updated `@binance/common` library to version `1.0.5`.

Release derivatives-trading-portfolio-margin-pro v6.0.0

---

common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/configuration.ts

- Fixed bug on `ConfigurationRestAPI` not respecting `baseOptions` parameters.

Release common v1.0.6

---

clients/sub-account/CHANGELOG.md
clients/sub-account/package-lock.json
clients/sub-account/package.json

Release sub-account v6.0.1

---

clients/simple-earn/CHANGELOG.md
clients/simple-earn/package-lock.json
clients/simple-earn/package.json

Release simple-earn v5.0.1

---

clients/margin-trading/CHANGELOG.md
clients/margin-trading/package-lock.json
clients/margin-trading/package.json

Release margin-trading v3.0.1

---

clients/dual-investment/CHANGELOG.md
clients/dual-investment/package-lock.json
clients/dual-investment/package.json

Release dual-investment v3.0.1

---

clients/derivatives-trading-portfolio-margin-pro/CHANGELOG.md
clients/derivatives-trading-portfolio-margin-pro/package-lock.json
clients/derivatives-trading-portfolio-margin-pro/package.json

Release derivatives-trading-portfolio-margin-pro v6.0.1

---

clients/derivatives-trading-options/CHANGELOG.md
clients/derivatives-trading-options/package-lock.json
clients/derivatives-trading-options/package.json

Release derivatives-trading-options v3.0.1

---

clients/margin-trading/CHANGELOG.md
clients/margin-trading/package-lock.json
clients/margin-trading/package.json
clients/margin-trading/src/rest-api/modules/trade-api.ts

- Fix bug with enums exporting.

Release margin-trading v4.0.0

---

clients/derivatives-trading-portfolio-margin-pro/CHANGELOG.md
clients/derivatives-trading-portfolio-margin-pro/package-lock.json
clients/derivatives-trading-portfolio-margin-pro/package.json

Release derivatives-trading-portfolio-margin-pro v6.0.2

---

clients/copy-trading/CHANGELOG.md
clients/copy-trading/package-lock.json
clients/copy-trading/package.json

Release copy-trading v2.0.2

---

clients/margin-trading/CHANGELOG.md
clients/margin-trading/package-lock.json
clients/margin-trading/package.json
clients/margin-trading/src/margin-trading.ts

Release margin-trading v5.0.1

---

clients/derivatives-trading-usds-futures/CHANGELOG.md
clients/derivatives-trading-usds-futures/package-lock.json
clients/derivatives-trading-usds-futures/package.json
clients/derivatives-trading-usds-futures/src/rest-api/types/exchange-information-response-assets-inner.ts
clients/derivatives-trading-usds-futures/src/rest-api/types/exchange-information-response-symbols-inner-filters-inner.ts
clients/derivatives-trading-usds-futures/tests/unit/rest-api/MarketDataApiTest.test.ts

- Modified response for `exchangeInformation()` method (`GET /fapi/v1/exchangeInfo`):
- `assets`.`autoAssetExchange`: type `integer` → `string`
- `symbols`.`filters`.`multiplierDecimal`: type `integer` → `string`

Release derivatives-trading-usds-futures v8.0.0

---

clients/derivatives-trading-options/CHANGELOG.md
clients/derivatives-trading-options/package-lock.json
clients/derivatives-trading-options/package.json

Release derivatives-trading-options v5.0.1

---

clients/derivatives-trading-portfolio-margin/CHANGELOG.md
clients/derivatives-trading-portfolio-margin/package-lock.json
clients/derivatives-trading-portfolio-margin/package.json

Release derivatives-trading-portfolio-margin v5.0.1

---

clients/margin-trading/CHANGELOG.md
clients/margin-trading/package-lock.json
clients/margin-trading/package.json

Release margin-trading v6.0.1

---

clients/derivatives-trading-usds-futures/CHANGELOG.md
clients/derivatives-trading-usds-futures/package-lock.json
clients/derivatives-trading-usds-futures/package.json

- Update `@binance/common` library to version `1.2.3`.

Release derivatives-trading-usds-futures v10.0.2

---

clients/derivatives-trading-coin-futures/CHANGELOG.md
clients/derivatives-trading-coin-futures/package-lock.json
clients/derivatives-trading-coin-futures/package.json

- Update `@binance/common` library to version `1.2.3`.

Release derivatives-trading-coin-futures v6.0.3

---

clients/derivatives-trading-portfolio-margin/CHANGELOG.md
clients/derivatives-trading-portfolio-margin/package-lock.json
clients/derivatives-trading-portfolio-margin/package.json

- Update `@binance/common` library to version `1.2.3`.

Release derivatives-trading-portfolio-margin v5.0.3
