binance/binance-connector-js

package-lock.json
package.json

We mistakenly reversed 2 dev packages versions in the package.json file, need to reverse it back.

reverse the version of dev dependencies in package.json file

---

CHANGELOG.md
package-lock.json
package.json

rc-v1.9.1 release

---

CHANGELOG.md
LICENSE.md
package-lock.json
package.json

v2.0.0 release

---

CHANGELOG.md
package-lock.json
package.json
src/modules/websocket.js

- Fixed WebSocket onClose event issue

v2.0.1 release

---

CHANGELOG.md
README.md
examples/spot/trade/account.js
examples/spot/trade/account_ed25519.js
examples/spot/trade/account_rsa.js
package-lock.json
package.json
src/APIBase.js
src/error/connectorClientError.js
src/helpers/privateKeyAlgo.js
src/index.js

- Support Ed25519 key signature

v3.0.0-rc.2 release

---

.github/workflows/node.js.yml
CHANGELOG.md
README.md
examples/websocketStream/spot/winstonLogLevel.js
package-lock.json
package.json
src/websocketBase.js

3.0.0 Release

---

types/CHANGELOG.md
types/package-lock.json
types/package.json

Release types v1.0.0

---

common/CHANGELOG.md
common/package-lock.json

Release common v1.0.0

---

clients/wallet/CHANGELOG.md
clients/wallet/package-lock.json
clients/wallet/package.json

Release wallet v1.0.0

---

clients/sub-account/CHANGELOG.md
clients/sub-account/package-lock.json
clients/sub-account/package.json

Release sub-account v1.0.0

---

clients/staking/CHANGELOG.md
clients/staking/package-lock.json
clients/staking/package.json

Release staking v1.0.0

---

clients/spot/CHANGELOG.md
clients/spot/package-lock.json
clients/spot/package.json

Release spot v1.0.0

---

clients/vip-loan/CHANGELOG.md
clients/vip-loan/package-lock.json
clients/vip-loan/package.json

Release vip-loan v1.0.0

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json

Release pay v1.0.0

---

clients/rebate/CHANGELOG.md
clients/rebate/package-lock.json
clients/rebate/package.json

Release rebate v1.0.0

---

clients/simple-earn/CHANGELOG.md
clients/simple-earn/package-lock.json
clients/simple-earn/package.json

Release simple-earn v1.0.0

---

clients/nft/CHANGELOG.md
clients/nft/package-lock.json
clients/nft/package.json

Release nft v1.0.0

---

clients/margin-trading/CHANGELOG.md
clients/margin-trading/package-lock.json
clients/margin-trading/package.json

Release margin-trading v1.0.0

---

clients/fiat/CHANGELOG.md
clients/fiat/package-lock.json
clients/fiat/package.json

Release fiat v1.0.0

---

clients/gift-card/CHANGELOG.md
clients/gift-card/package-lock.json
clients/gift-card/package.json

Release gift-card v1.0.0

---

clients/mining/CHANGELOG.md
clients/mining/package-lock.json
clients/mining/package.json

Release mining v1.0.0

---

clients/derivatives-trading-portfolio-margin/CHANGELOG.md
clients/derivatives-trading-portfolio-margin/package-lock.json
clients/derivatives-trading-portfolio-margin/package.json

Release derivatives-trading-portfolio-margin v1.0.0

---

clients/derivatives-trading-portfolio-margin-pro/CHANGELOG.md
clients/derivatives-trading-portfolio-margin-pro/package-lock.json
clients/derivatives-trading-portfolio-margin-pro/package.json

Release derivatives-trading-portfolio-margin-pro v1.0.0

---

clients/dual-investment/CHANGELOG.md
clients/dual-investment/package-lock.json
clients/dual-investment/package.json

Release dual-investment v1.0.0

---

clients/derivatives-trading-usds-futures/CHANGELOG.md
clients/derivatives-trading-usds-futures/package-lock.json
clients/derivatives-trading-usds-futures/package.json

Release derivatives-trading-usds-futures v1.0.0

---

clients/derivatives-trading-options/CHANGELOG.md
clients/derivatives-trading-options/package-lock.json
clients/derivatives-trading-options/package.json

Release derivatives-trading-options v1.0.0

---

clients/crypto-loan/CHANGELOG.md
clients/crypto-loan/package-lock.json
clients/crypto-loan/package.json

Release crypto-loan v1.0.0

---

clients/copy-trading/CHANGELOG.md
clients/copy-trading/package-lock.json
clients/copy-trading/package.json

Release copy-trading v1.0.0

---

clients/c2c/CHANGELOG.md
clients/c2c/package-lock.json
clients/c2c/package.json

Release c2c v1.0.0

---

clients/auto-invest/CHANGELOG.md
clients/auto-invest/package-lock.json
clients/auto-invest/package.json

Release auto-invest v1.0.0

---

clients/algo/CHANGELOG.md
clients/algo/package-lock.json
clients/algo/package.json

Release algo v1.0.0

---

.github/workflows/ci.yaml
common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/constants.ts
common/src/utils.ts
common/tests/UtilsTest.test.ts

- Fix bug on `httpRequestFunction` error parsing.
- Remove unsupported Testnet URLs for `/sapi` BUs.

Release common v1.0.1

---

clients/wallet/CHANGELOG.md
clients/wallet/README.md
clients/wallet/package-lock.json
clients/wallet/package.json
clients/wallet/src/index.ts

Release wallet v2.0.1

---

clients/pay/CHANGELOG.md
clients/pay/README.md
clients/pay/package-lock.json
clients/pay/package.json
clients/pay/src/index.ts
clients/pay/src/rest-api/index.ts
clients/pay/src/rest-api/modules/index.ts
clients/pay/src/rest-api/modules/pay-api.ts
clients/pay/src/rest-api/rest-api.ts
clients/pay/src/rest-api/types/bad-request.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner-funds-detail-inner-wallet-asset-cost-inner.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner-funds-detail-inner.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner-payer-info.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner-receiver-info-extend.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner-receiver-info.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response-data-inner.ts
clients/pay/src/rest-api/types/get-pay-trade-history-response.ts
clients/pay/tests/unit/rest-api/PayApiTest.test.ts

Release pay v1.0.1

---

clients/gift-card/CHANGELOG.md
clients/gift-card/README.md
clients/gift-card/package-lock.json
clients/gift-card/package.json
clients/gift-card/src/index.ts
clients/gift-card/src/rest-api/index.ts
clients/gift-card/src/rest-api/modules/index.ts
clients/gift-card/src/rest-api/modules/market-data-api.ts
clients/gift-card/src/rest-api/rest-api.ts
clients/gift-card/src/rest-api/types/bad-request.ts
clients/gift-card/src/rest-api/types/create-adual-token-gift-card-response-data.ts
clients/gift-card/src/rest-api/types/create-adual-token-gift-card-response.ts
clients/gift-card/src/rest-api/types/create-asingle-token-gift-card-response.ts
clients/gift-card/src/rest-api/types/fetch-rsa-public-key-response.ts
clients/gift-card/src/rest-api/types/fetch-token-limit-response-data-inner.ts
clients/gift-card/src/rest-api/types/fetch-token-limit-response.ts
clients/gift-card/src/rest-api/types/redeem-abinance-gift-card-response-data.ts
clients/gift-card/src/rest-api/types/redeem-abinance-gift-card-response.ts
clients/gift-card/src/rest-api/types/verify-binance-gift-card-by-gift-card-number-response-data.ts
clients/gift-card/src/rest-api/types/verify-binance-gift-card-by-gift-card-number-response.ts
clients/gift-card/tests/unit/rest-api/MarketDataApiTest.test.ts

Release gift-card v1.0.1

---

clients/fiat/CHANGELOG.md
clients/fiat/README.md
clients/fiat/package-lock.json
clients/fiat/package.json
clients/fiat/src/index.ts
clients/fiat/src/rest-api/index.ts
clients/fiat/src/rest-api/modules/fiat-api.ts
clients/fiat/src/rest-api/modules/index.ts
clients/fiat/src/rest-api/rest-api.ts
clients/fiat/src/rest-api/types/bad-request.ts
clients/fiat/src/rest-api/types/get-fiat-deposit-withdraw-history-response-data-inner.ts
clients/fiat/src/rest-api/types/get-fiat-deposit-withdraw-history-response.ts
clients/fiat/src/rest-api/types/get-fiat-payments-history-response-data-inner.ts
clients/fiat/src/rest-api/types/get-fiat-payments-history-response.ts
clients/fiat/tests/unit/rest-api/FiatApiTest.test.ts

Release fiat v1.0.1

---

types/CHANGELOG.md
types/package-lock.json
types/package.json

Release types v1.0.1

---

clients/convert/CHANGELOG.md
clients/convert/README.md
clients/convert/package-lock.json
clients/convert/package.json
clients/convert/src/index.ts
clients/convert/src/rest-api/index.ts
clients/convert/src/rest-api/modules/index.ts
clients/convert/src/rest-api/modules/market-data-api.ts
clients/convert/src/rest-api/modules/trade-api.ts
clients/convert/src/rest-api/rest-api.ts
clients/convert/src/rest-api/types/accept-quote-response.ts
clients/convert/src/rest-api/types/bad-request.ts
clients/convert/src/rest-api/types/cancel-limit-order-response.ts
clients/convert/src/rest-api/types/get-convert-trade-history-response-list-inner.ts
clients/convert/src/rest-api/types/get-convert-trade-history-response.ts
clients/convert/src/rest-api/types/list-all-convert-pairs-response-inner.ts
clients/convert/src/rest-api/types/list-all-convert-pairs-response.ts
clients/convert/src/rest-api/types/order-status-response.ts
clients/convert/src/rest-api/types/place-limit-order-response.ts
clients/convert/src/rest-api/types/query-limit-open-orders-response-list-inner.ts
clients/convert/src/rest-api/types/query-limit-open-orders-response.ts
clients/convert/src/rest-api/types/query-order-quantity-precision-per-asset-response-inner.ts
clients/convert/src/rest-api/types/query-order-quantity-precision-per-asset-response.ts
clients/convert/src/rest-api/types/send-quote-request-response.ts
clients/convert/tests/unit/rest-api/MarketDataApiTest.test.ts
clients/convert/tests/unit/rest-api/TradeApiTest.test.ts

Release convert v1.0.1

---

clients/algo/CHANGELOG.md
clients/algo/README.md
clients/algo/package-lock.json
clients/algo/package.json
clients/algo/src/index.ts
clients/algo/src/rest-api/index.ts
clients/algo/src/rest-api/modules/future-algo-api.ts
clients/algo/src/rest-api/modules/index.ts
clients/algo/src/rest-api/modules/spot-algo-api.ts
clients/algo/src/rest-api/rest-api.ts
clients/algo/src/rest-api/types/bad-request.ts
clients/algo/src/rest-api/types/cancel-algo-order-future-algo-response.ts
clients/algo/src/rest-api/types/cancel-algo-order-spot-algo-response.ts
clients/algo/src/rest-api/types/query-current-algo-open-orders-future-algo-response-orders-inner.ts
clients/algo/src/rest-api/types/query-current-algo-open-orders-future-algo-response.ts
clients/algo/src/rest-api/types/query-current-algo-open-orders-spot-algo-response-orders-inner.ts
clients/algo/src/rest-api/types/query-current-algo-open-orders-spot-algo-response.ts
clients/algo/src/rest-api/types/query-historical-algo-orders-future-algo-response-orders-inner.ts
clients/algo/src/rest-api/types/query-historical-algo-orders-future-algo-response.ts
clients/algo/src/rest-api/types/query-historical-algo-orders-spot-algo-response-orders-inner.ts
clients/algo/src/rest-api/types/query-historical-algo-orders-spot-algo-response.ts
clients/algo/src/rest-api/types/query-sub-orders-future-algo-response-sub-orders-inner.ts
clients/algo/src/rest-api/types/query-sub-orders-future-algo-response.ts
clients/algo/src/rest-api/types/query-sub-orders-spot-algo-response.ts
clients/algo/src/rest-api/types/time-weighted-average-price-future-algo-response.ts
clients/algo/src/rest-api/types/time-weighted-average-price-spot-algo-response.ts
clients/algo/src/rest-api/types/volume-participation-future-algo-response.ts
clients/algo/tests/unit/rest-api/FutureAlgoApiTest.test.ts
clients/algo/tests/unit/rest-api/SpotAlgoApiTest.test.ts

Release algo v1.0.1

---

common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/utils.ts
common/tests/UtilsTest.test.ts
common/tsup.config.ts

- Update `replaceWebsocketStreamsPlaceholders` function to parse `updateSpeed` properly.

Release common v1.0.2

---

clients/sub-account/CHANGELOG.md
clients/sub-account/package-lock.json
clients/sub-account/package.json
clients/sub-account/src/rest-api/modules/account-management-api.ts
clients/sub-account/src/rest-api/modules/api-management-api.ts
clients/sub-account/src/rest-api/modules/asset-management-api.ts

- Correctly marked endpoints as signed.

Release sub-account v3.0.1

---

clients/sub-account/CHANGELOG.md
clients/sub-account/package-lock.json
clients/sub-account/package.json
clients/sub-account/src/rest-api/modules/account-management-api.ts
clients/sub-account/src/rest-api/modules/api-management-api.ts
clients/sub-account/src/rest-api/modules/asset-management-api.ts
clients/sub-account/src/rest-api/modules/managed-sub-account-api.ts
clients/sub-account/src/rest-api/rest-api.ts

- Marked as signed the following endpoints:
- `GET /sapi/v1/sub-account/transfer/subUserHistory`
- `POST /sapi/v1/sub-account/transfer/subToMaster`
- `POST /sapi/v1/sub-account/transfer/subToSub`
- `POST /sapi/v1/managed-subaccount/deposit`
- `GET /sapi/v1/managed-subaccount/asset`
- `GET /sapi/v1/managed-subaccount/accountSnapshot`
- `POST /sapi/v1/managed-subaccount/withdraw`

Release sub-account v4.0.0

---

clients/spot/CHANGELOG.md
clients/spot/package-lock.json
clients/spot/package.json
clients/spot/src/rest-api/modules/general-api.ts
clients/spot/src/rest-api/modules/trade-api.ts
clients/spot/src/rest-api/rest-api.ts
clients/spot/src/websocket-api/modules/general-api.ts
clients/spot/src/websocket-api/modules/trade-api.ts
clients/spot/src/websocket-api/websocket-api-connection.ts
clients/spot/tests/unit/rest-api/GeneralApiTest.test.ts

- Updated enums for General and Trade APIs.

Release spot v3.0.0

---

common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/utils.ts
common/src/websocket.ts
common/tests/WebsocketTest.test.ts

- Support streams on Websocket APIs.

Release common v1.0.4

---

clients/crypto-loan/CHANGELOG.md
clients/crypto-loan/package-lock.json
clients/crypto-loan/package.json
clients/crypto-loan/src/rest-api/modules/flexible-rate-api.ts
clients/crypto-loan/tests/unit/rest-api/FlexibleRateApiTest.test.ts

- Added parameter `repaymentType` for `flexibleLoanRepay()` (`POST /sapi/v2/loan/flexible/repay`)

Release crypto-loan v4.0.0

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json
clients/pay/src/rest-api/modules/pay-api.ts

- Marked as signed the following endpoints:
- `GET /sapi/v1/pay/transactions`

Release pay v3.0.0

---

clients/staking/CHANGELOG.md
clients/staking/package-lock.json
clients/staking/package.json

Release staking v2.0.1

---

clients/spot/CHANGELOG.md
clients/spot/package-lock.json
clients/spot/package.json

Release spot v6.0.1

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json

Release pay v3.0.1

---

clients/nft/CHANGELOG.md
clients/nft/package-lock.json
clients/nft/package.json

Release nft v2.0.1

---

clients/gift-card/CHANGELOG.md
clients/gift-card/package-lock.json
clients/gift-card/package.json

Release gift-card v2.0.1

---

clients/crypto-loan/CHANGELOG.md
clients/crypto-loan/package-lock.json
clients/crypto-loan/package.json

Release crypto-loan v6.0.1

---

clients/convert/CHANGELOG.md
clients/convert/package-lock.json
clients/convert/package.json

Release convert v2.0.1

---

clients/staking/CHANGELOG.md
clients/staking/package-lock.json
clients/staking/package.json

Release staking v2.0.2

---

clients/simple-earn/CHANGELOG.md
clients/simple-earn/package-lock.json
clients/simple-earn/package.json

Release simple-earn v5.0.2

---

clients/rebate/CHANGELOG.md
clients/rebate/package-lock.json
clients/rebate/package.json

Release rebate v2.0.2

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json

Release pay v3.0.2

---

clients/gift-card/CHANGELOG.md
clients/gift-card/package-lock.json
clients/gift-card/package.json

Release gift-card v2.0.2

---

clients/fiat/CHANGELOG.md
clients/fiat/package-lock.json
clients/fiat/package.json

Release fiat v2.0.2

---

clients/dual-investment/CHANGELOG.md
clients/dual-investment/package-lock.json
clients/dual-investment/package.json

Release dual-investment v3.0.2

---

clients/derivatives-trading-portfolio-margin/CHANGELOG.md
clients/derivatives-trading-portfolio-margin/package-lock.json
clients/derivatives-trading-portfolio-margin/package.json
clients/derivatives-trading-portfolio-margin/src/rest-api/modules/trade-api.ts

- Fix bug with enums exporting.

Release derivatives-trading-portfolio-margin v4.0.0

---

clients/convert/CHANGELOG.md
clients/convert/package-lock.json
clients/convert/package.json

Release convert v2.0.2

---

clients/crypto-loan/CHANGELOG.md
clients/crypto-loan/package-lock.json
clients/crypto-loan/package.json

Release crypto-loan v6.0.2

---

clients/c2c/CHANGELOG.md
clients/c2c/package-lock.json
clients/c2c/package.json

Release c2c v2.0.2

---

clients/algo/CHANGELOG.md
clients/algo/package-lock.json
clients/algo/package.json

Release algo v2.0.2

---

clients/auto-invest/CHANGELOG.md
clients/auto-invest/package-lock.json
clients/auto-invest/package.json

Release auto-invest v2.0.2

---

common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/configuration.ts
common/src/utils.ts
common/tests/UtilsTest.test.ts

- Modified `keepAlive` logic to respect `httpsAgent` configuration if set.
- Exposed `ws` TS types.
- Fixed bug with array stringification on REST API requests.
- Cache signature generation.

Release common v1.1.1

---

clients/c2c/CHANGELOG.md
clients/c2c/package-lock.json
clients/c2c/package.json
clients/c2c/src/c2c.ts

Release c2c v2.0.4

---

clients/convert/CHANGELOG.md
clients/convert/examples/rest-api/TradeApi/placeLimitOrder.ts
clients/convert/package-lock.json
clients/convert/package.json
clients/convert/src/convert.ts
clients/convert/src/rest-api/modules/trade-api.ts
clients/convert/tests/unit/rest-api/TradeApiTest.test.ts

Release convert v2.0.4

---

clients/algo/CHANGELOG.md
clients/algo/examples/rest-api/FutureAlgoApi/timeWeightedAveragePriceFutureAlgo.ts
clients/algo/examples/rest-api/FutureAlgoApi/volumeParticipationFutureAlgo.ts
clients/algo/examples/rest-api/SpotAlgoApi/timeWeightedAveragePriceSpotAlgo.ts
clients/algo/package-lock.json
clients/algo/package.json
clients/algo/src/algo.ts
clients/algo/tests/unit/rest-api/FutureAlgoApiTest.test.ts
clients/algo/tests/unit/rest-api/SpotAlgoApiTest.test.ts

Release algo v2.0.4

---

clients/crypto-loan/CHANGELOG.md
clients/crypto-loan/examples/rest-api/FlexibleRateApi/flexibleLoanAdjustLtv.ts
clients/crypto-loan/examples/rest-api/FlexibleRateApi/flexibleLoanRepay.ts
clients/crypto-loan/examples/rest-api/StableRateApi/checkCollateralRepayRateStableRate.ts
clients/crypto-loan/package-lock.json
clients/crypto-loan/package.json
clients/crypto-loan/src/crypto-loan.ts
clients/crypto-loan/tests/unit/rest-api/FlexibleRateApiTest.test.ts
clients/crypto-loan/tests/unit/rest-api/StableRateApiTest.test.ts

Release crypto-loan v6.0.4

---

clients/derivatives-trading-coin-futures/CHANGELOG.md
clients/derivatives-trading-coin-futures/examples/rest-api/TradeApi/modifyIsolatedPositionMargin.ts
clients/derivatives-trading-coin-futures/examples/websocket-api/TradeApi/modifyOrder.ts
clients/derivatives-trading-coin-futures/package-lock.json
clients/derivatives-trading-coin-futures/package.json
clients/derivatives-trading-coin-futures/src/derivatives-trading-coin-futures.ts
clients/derivatives-trading-coin-futures/tests/unit/rest-api/TradeApiTest.test.ts
clients/derivatives-trading-coin-futures/tests/unit/websocket-api/TradeApiTest.test.ts

Release derivatives-trading-coin-futures v5.0.2

---

clients/derivatives-trading-options/CHANGELOG.md
clients/derivatives-trading-options/examples/rest-api/MarketMakerBlockTradeApi/newBlockTradeOrder.ts
clients/derivatives-trading-options/examples/rest-api/TradeApi/newOrder.ts
clients/derivatives-trading-options/package-lock.json
clients/derivatives-trading-options/package.json
clients/derivatives-trading-options/src/derivatives-trading-options.ts
clients/derivatives-trading-options/tests/unit/rest-api/MarketMakerBlockTradeApiTest.test.ts
clients/derivatives-trading-options/tests/unit/rest-api/MarketMakerEndpointsApiTest.test.ts
clients/derivatives-trading-options/tests/unit/rest-api/TradeApiTest.test.ts

Release derivatives-trading-options v4.0.2

---

clients/derivatives-trading-usds-futures/CHANGELOG.md
clients/derivatives-trading-usds-futures/examples/rest-api/TradeApi/modifyIsolatedPositionMargin.ts
clients/derivatives-trading-usds-futures/examples/rest-api/TradeApi/modifyOrder.ts
clients/derivatives-trading-usds-futures/examples/websocket-api/TradeApi/modifyOrder.ts
clients/derivatives-trading-usds-futures/package-lock.json
clients/derivatives-trading-usds-futures/package.json
clients/derivatives-trading-usds-futures/src/derivatives-trading-usds-futures.ts
clients/derivatives-trading-usds-futures/tests/unit/rest-api/ConvertApiTest.test.ts
clients/derivatives-trading-usds-futures/tests/unit/rest-api/TradeApiTest.test.ts
clients/derivatives-trading-usds-futures/tests/unit/websocket-api/TradeApiTest.test.ts

Release derivatives-trading-usds-futures v7.0.2

---

clients/derivatives-trading-portfolio-margin/CHANGELOG.md
clients/derivatives-trading-portfolio-margin/examples/rest-api/AccountApi/bnbTransfer.ts
clients/derivatives-trading-portfolio-margin/examples/rest-api/TradeApi/marginAccountBorrow.ts
clients/derivatives-trading-portfolio-margin/examples/rest-api/TradeApi/marginAccountNewOco.ts
clients/derivatives-trading-portfolio-margin/examples/rest-api/TradeApi/marginAccountRepay.ts
clients/derivatives-trading-portfolio-margin/examples/rest-api/TradeApi/modifyCmOrder.ts
clients/derivatives-trading-portfolio-margin/examples/rest-api/TradeApi/modifyUmOrder.ts
clients/derivatives-trading-portfolio-margin/package-lock.json
clients/derivatives-trading-portfolio-margin/package.json
clients/derivatives-trading-portfolio-margin/src/derivatives-trading-portfolio-margin.ts
clients/derivatives-trading-portfolio-margin/tests/unit/rest-api/AccountApiTest.test.ts
clients/derivatives-trading-portfolio-margin/tests/unit/rest-api/TradeApiTest.test.ts

Release derivatives-trading-portfolio-margin v4.0.2

---

clients/mining/CHANGELOG.md
clients/mining/package-lock.json
clients/mining/package.json
clients/mining/src/mining.ts

Release mining v3.0.4

---

clients/gift-card/CHANGELOG.md
clients/gift-card/examples/rest-api/MarketDataApi/createADualTokenGiftCard.ts
clients/gift-card/examples/rest-api/MarketDataApi/createASingleTokenGiftCard.ts
clients/gift-card/package-lock.json
clients/gift-card/package.json
clients/gift-card/src/gift-card.ts
clients/gift-card/src/rest-api/modules/market-data-api.ts
clients/gift-card/src/rest-api/rest-api.ts
clients/gift-card/tests/unit/rest-api/MarketDataApiTest.test.ts

Release gift-card v2.0.4

---

clients/rebate/CHANGELOG.md
clients/rebate/package-lock.json
clients/rebate/package.json
clients/rebate/src/rebate.ts

Release rebate v2.0.4

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json
clients/pay/src/pay.ts

Release pay v3.0.4

---

clients/sub-account/CHANGELOG.md
clients/sub-account/examples/rest-api/AssetManagementApi/futuresTransferForSubAccount.ts
clients/sub-account/examples/rest-api/AssetManagementApi/marginTransferForSubAccount.ts
clients/sub-account/examples/rest-api/AssetManagementApi/subAccountFuturesAssetTransfer.ts
clients/sub-account/examples/rest-api/AssetManagementApi/transferToMaster.ts
clients/sub-account/examples/rest-api/AssetManagementApi/transferToSubAccountOfSameMaster.ts
clients/sub-account/examples/rest-api/AssetManagementApi/universalTransfer.ts
clients/sub-account/examples/rest-api/ManagedSubAccountApi/depositAssetsIntoTheManagedSubAccount.ts
clients/sub-account/examples/rest-api/ManagedSubAccountApi/withdrawlAssetsFromTheManagedSubAccount.ts
clients/sub-account/package-lock.json
clients/sub-account/package.json
clients/sub-account/src/sub-account.ts
clients/sub-account/tests/unit/rest-api/AssetManagementApiTest.test.ts
clients/sub-account/tests/unit/rest-api/ManagedSubAccountApiTest.test.ts

Release sub-account v7.0.2

---

common/CHANGELOG.md
common/package-lock.json
common/package.json
common/src/configuration.ts
common/src/utils.ts
common/src/websocket.ts
common/tests/UtilsTest.test.ts
common/tests/WebsocketTest.test.ts

- Support custom Headers on REST API requests (`customHeaders` option on `ConfigurationRestAPI`).
- Support automatic session re-logon on reconncetions/renewals when session is already logged on (`autoSessionReLogon` option on `ConfigurationWebsocketAPI`).

Release common v1.2.0

---

types/CHANGELOG.md
types/package-lock.json
types/package.json

Release types v1.0.3

---

clients/mining/CHANGELOG.md
clients/mining/package-lock.json
clients/mining/package.json

Release mining v3.0.5

---

clients/nft/CHANGELOG.md
clients/nft/package-lock.json
clients/nft/package.json

Release nft v2.0.5

---

clients/pay/CHANGELOG.md
clients/pay/package-lock.json
clients/pay/package.json

Release pay v3.0.5

---

clients/sub-account/CHANGELOG.md
clients/sub-account/package-lock.json
clients/sub-account/package.json

Release sub-account v7.0.3

---

clients/wallet/CHANGELOG.md
clients/wallet/package-lock.json
clients/wallet/package.json

Release wallet v6.0.3

---

clients/spot/CHANGELOG.md
clients/spot/package-lock.json
clients/spot/package.json

- Update `@binance/common` library to version `1.2.3`.

Release spot v13.0.1
